### ISSUE TITLE
Different Problems

### ISSUE THREAD

**Issue by dagobert666** [PKISolutions/PsFCIV#1]
Hello,
i had different problems with your cmdlet:
when the startfolder has no files and only a subfolder it seems that it doesnt work. (also with -Recurse)
when i specify the xml file in c:\ folder (c:\test.xml) its not working. (with admin rights).
often PsFCIV show no results, it show nothing.

Please help.
Thank you

**Comment by Crypt32** [comment]
can you provide full command you call and output you get in each scenario?

**Comment by Crypt32** [comment]
Closing this as duplicate (although this issue is started first). Requested information was received in #3 and fixed as part of that issue.
