### ISSUE TITLE
Two zero byte files crash the Checking function

### ISSUE THREAD

**Issue by TheRedeemer** [PKISolutions/PsFCIV#2]
Hello Mr. Podans,

I am very interested in migrating away from Microsoft's FCIV and over to your PsFCIV due to its support of more secure hashing algorithms, i.e. SHA256.

I was initially testing PsFCIV on a data set of 130 megabytes, 267 Files, 89 Folders.  The DB.xml generated successfully but a second run for Checking the files was crashing.  In this case there were Two zero byte files hiding in different locations in the data, not even next to one another.

I'm able to reproduce the crash on a small scaled down example of just 3 text files, one having text, the other two having zero bytes.  Below are the commands and output.  Attached is tmp.zip containing the samller example files and db.xml

Thank You!

*************************************************************************************************************

PS C:\> Start-PsFCIV -Path "C:\tmp" -XML "C:\Users\Owner\Desktop\DB.xml" -HashAlgorithm SHA1 -Recurse -Verbose

VERBOSE: Perform file 'C:\tmp\file1_does_have_text_inside.txt' checking.
VERBOSE: Perform file 'C:\tmp\file2_ZERO_bytes.txt' checking.
VERBOSE: Perform file 'C:\tmp\file3_ZERO_bytes.txt' checking.

Total files processed      : 3
Total new added files      : 3
Total good files           : 0
Total bad files            : 0
Total unknown status files : 0
Total missing files        : 0
Total locked files         : 0

Total   : 3
New     : 3
Ok      : 0
Bad     : 0
Missed  : 0
Locked  : 0
Unknown : 0
Deleted : 0

PS C:\> Start-PsFCIV -Path "C:\tmp" -XML "C:\Users\Owner\Desktop\DB.xml" -HashAlgorithm SHA1 -Recurse -Verbose

VERBOSE: Perform file 'C:\tmp\file1_does_have_text_inside.txt C:\tmp\file2_ZERO_bytes.txt C:\tmp\file3_ZERO_bytes.txt'
checking.
VERBOSE: File file1_does_have_text_inside.txt file2_ZERO_bytes.txt **file3_ZERO_bytes.txt is locked. Skipping this file..**

PS C:\>

*************************************************************************************************************

[tmp.zip](https://github.com/PKISolutions/PsFCIV/files/7653209/tmp.zip)
[](url)

**Comment by Crypt32** [comment]
Thanks for report, I will investigate this. I'm not sure if I ever tested against zero-byte files, so this certainly can be a bug.

**Comment by Crypt32** [comment]
Hi, sorry for late response.

Finally I've found a time to work on your issue. It appears there are several issues in the code:

1. I'm incorrectly detecting the FCIV mode (native or legacy). I'm examining `Size` property in XML database which doesn't exist in legacy FCIV and put the script in legacy FCIV processing mode if its value equals to 0 (default for `Int64`). However, file itself can have zero size. I moved detection to `Timestamp` property which is more reliable in this case, because it is `$null` for legacy 
2. when legacy mode is ON, I'm using `for` loop to iterate over entries in DB and access them by index. However, `$db.Entries` is of type of `ISet<T>` which doesn't have an indexer.
3. `for` loop contains several `return` statements which are meant to be `continue`.

maybe there are other issues.

**Comment by TheRedeemer** [comment]
No rush.  I'm just happy you are continuing development of this awesome program.

Thanks for stepping through the code and identifying these different legacy mode issues.

I keep checking back every so often on GitHub and PowerShell Gallery to see if there is a new version of PsFCIV to try out.

**Comment by Crypt32** [comment]
Hello, hope you are well. I believe I've fixed your issue. If you wouldn't mind, please check the most recent version of [Start-PsFCIV.ps1](https://github.com/PKISolutions/PsFCIV/blob/master/PsFCIV/Start-PsFCIV.ps1) file from this repo and confirm if issue is resolved. If it is, I will update the release on PowerShell Gallery.

There is another

**Comment by TheRedeemer** [comment]
Happy New Year!

Great!!  I've tested the updated code against my data set containing zero byte files, and it now works perfectly while checking DB.xml

Thanks again for looking into this.

**Comment by Crypt32** [comment]
I just want to let you know that updated version is published to PowerShell Gallery as v1.1.

**Comment by jacky8301** [comment]
how store the file relative path in db, but not the absolute path
