### ISSUE TITLE
The -Recurse switch is not honored when hashing a set of directories

### ISSUE THREAD

**Issue by TheRedeemer** [PKISolutions/PsFCIV#3]
Hello, hope all is well.  This issue is actually a duplicate of the main issue mentioned in issue #1 I am separating it out so it is not bundled with any other problem.

Sorry in advance for any bad formatting in this report.

I've been researching it and have come up with an explanation and possible solution.

I ran into this problem when trying to hash a data set containing 25 folders, 166 Gigs of data.  Each folder had its own sets of files and subfolders of course, but the problem was that the program expects at least 1 file at the Path location, or the program exits without hashing.

I traced the issue to a strange behavior of the Get-ChildItem cmdlet.  If Get-ChildItem is called with BOTH the -Recurse and -File parameters it will return nothing and not traverse any  subdirectories unless 1 or more files is present at the working directory level.

**********************************************************************************************
As a small example lets say this is my data set:
C:\working_directory\folder1\file1.txt
C:\working_directory\folder2\an empty subfolder\
C:\working_directory\folder3\file3.txt
**********************************************************************************************
I try to recurse and nothing is returned:
PS C:\working_directory> Get-ChildItem -Path .\\* -Filter * -Recurse -Force -File
PS C:\working_directory>
**********************************************************************************************
Now I try again without the -File paramenter:
PS C:\working_directory> Get-ChildItem -Path .\\* -Filter * -Recurse -Force

    Directory: C:\working_directory\folder1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/14/2022   4:39 PM             12 file1.txt

    Directory: C:\working_directory\folder2

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/14/2022   6:12 PM                an empty subfolder

    Directory: C:\working_directory\folder3

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/14/2022   4:39 PM             12 file3.txt

This time the Recursion is successful but a directory is also returned which we do not want.

**********************************************************************************************

Finally I try:
PS C:\working_directory> Get-ChildItem -Path .\\* -Filter * -Recurse -Force | where { ! $_.PSIsContainer }

    Directory: C:\working_directory\folder1

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/14/2022   4:39 PM             12 file1.txt

    Directory: C:\working_directory\folder3

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        1/14/2022   4:39 PM             12 file3.txt

And here the recursion is successful and the directories are omitted. 

**********************************************************************************************

Supposedly the $_.PSIsContainer property is only false in Files, not directories or symlinks so this can be used to obtain the File list instead of using the -File parameter itself.

https://github.com/PKISolutions/PsFCIV/blob/7ef7b1f90840cfbde6506f03babf8f7e9ac00163/PsFCIV/PsFCIV.psm1#L28
So you may try changing line 28 in PsFCIV.psm1 as such:

Original:
# lightweight proxy function for Get-ChildItem cmdlet
function dirx ([string]$Path, [string]$Filter, [string[]]$Exclude, $Recurse, [switch]$Force) {
    Get-ChildItem @PSBoundParameters -File -ErrorAction SilentlyContinue
}

Modified:
# lightweight proxy function for Get-ChildItem cmdlet
function dirx ([string]$Path, [string]$Filter, [string[]]$Exclude, $Recurse, [switch]$Force) {
    Get-ChildItem @PSBoundParameters -ErrorAction SilentlyContinue | where { ! $_.PSIsContainer }
}

[working_directory.zip](https://github.com/PKISolutions/PsFCIV/files/7874096/working_directory.zip)

**Comment by Crypt32** [comment]
I can confirm that your proposed changes make a difference. Applied in source code.
