### ISSUE TITLE
A special character in a file name causes a <FILE_ENTRY> to be omitted from DB.xml without notifying user.

### ISSUE THREAD

**Issue by TheRedeemer** [PKISolutions/PsFCIV#5]
Hello, hope all is well.  I was testing PsFCIV on some real-world examples, My Documents containing 16,535 Files, 1,050 Folders.  All seemed OK at first, "Total files processed" and "Total new added files" both indicated 16,535, and the Verbose output also printed that many lines.

But when I passed DB.xml through a program to count <FILE_ENTRY> tags, 16,534 Files came back.  I traced the issue to one file name containing something that seems like a hyphen but is not.  Attached is a smaller data set containing the problem file name.  As a matter of fact, the github form isn't even displaying the character as I try to paste it, so check the attached .zip

PS C:\test\data_set> Start-PsFCIV -Path .\ -Include * -XML "C:\test\DB.xml" -HashAlgorithm MD5 -Recurse -Verbose
VERBOSE: Perform file 'C:\test\data_set\Barn Owl.txt' checking.
VERBOSE: Perform file 'C:\test\data_set\Barn_Owl.txt' checking.
VERBOSE: Perform file 'C:\test\data_set\Barn­_Owl.txt' checking.
-----------------------------------
Total files processed      : 3
Total new added files      : 3
Total good files           : 0
Total bad files            : 0
Total unknown status files : 0
Total missing files        : 0
Total locked files         : 0
-----------------------------------

Total   : 3
New     : 3
Ok      : 0
Bad     : 0
Missed  : 0
Locked  : 0
Unknown : 0
Deleted : 0

Notice only Two <FILE_ENTRY>'s are actually written to DB.xml

`<FCIV>
<FILE_ENTRY>
<name>Barn Owl.txt</name>
<Size>12</Size>
<TimeStamp>01/18/2022 07:49:28</TimeStamp>
<MD5>HIkS05fEaGZwazcMovokbQ==</MD5>
</FILE_ENTRY>
<FILE_ENTRY>
<name>Barn_Owl.txt</name>
<Size>16</Size>
<TimeStamp>01/18/2022 07:49:41</TimeStamp>
<MD5>NYX+pTjx8Ee6bzjBC+hyLQ==</MD5>
</FILE_ENTRY>
</FCIV>`

Thanks again for making this program available, it is still very useful even with current issues.

[TEST.zip](https://github.com/PKISolutions/PsFCIV/files/7887721/TEST.zip)

**Comment by Crypt32** [comment]
To speed up the lookup process and avoid potential duplicate entries I'm using a hash set to store entries. This requires that every entry's name is unique within a collection and duplicates are not inserted (although counted in stats as inserted and it is the result of my lazyness).

The actual issue is in how file names are compared. I'm using this one https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparer.invariantcultureignorecase when checking if such file is already processed. In your case, this comparer thinks that last two file names in your attachment are identical, thus second file although has different name, comparison thinks they are identical. You can test it yourself against your data set:

```
$list = dir .\DATA_SET
[string]::equals($list[1].Name, $list[2].Name,"InvariantCultureIgnoreCase") # will return $true
```
It seems I have to replace comparison option from invariant culture to ordinal. Though, cultures are hard to deal with and I didn't test such scenarios.

**Comment by Crypt32** [comment]
I think I've fixed this and fix works against your data set. Wouldn't you mind to grab this library and test it in your environment: https://github.com/PKISolutions/PsFCIV/tree/master/PsFCIV/lib. Replace the file stored in "lib" folder in module installation directory.

**Comment by TheRedeemer** [comment]
Great!  The change worked for my data set.

test run to create DB.xml

PS C:\temp\TESTING_ZONE\My Documents Backup 01-13-2022> Start-PsFCIV -Path .\ -XML "C:\temp\TESTING_ZONE\DB.xml" -HashAlgorithm MD5 -Recurse -Verbose

-----------------------------------
Total files processed      : 16535
Total new added files      : 16535
Total good files           : 0
Total bad files            : 0
Total unknown status files : 0
Total missing files        : 0
Total locked files         : 0
-----------------------------------


Total   : 16535
New     : 16535
Ok      : 0
Bad     : 0
Missed  : 0
Locked  : 0
Unknown : 0
Deleted : 0


Now double checking <FILE_ENTRY> tag count:

C:\temp\TESTING_ZONE>java StringCount "<FILE_ENTRY>" ".\DB.xml"

<FILE_ENTRY> was found 16535 times.

I also checked the name element containing the international character, and it is preserved OK in the DB.xml



Finally another run in checking mode:

PS C:\temp\TESTING_ZONE\My Documents Backup 01-13-2022> Start-PsFCIV -Path .\ -XML "C:\temp\TESTING_ZONE\DB.xml" -HashAlgorithm MD5 -Recurse -Verbose


-----------------------------------
Total files processed      : 16535
Total good files           : 16535
Total bad files            : 0
Total unknown status files : 0
Total missing files        : 0
Total locked files         : 0
-----------------------------------


Total   : 16535
New     : 0
Ok      : 16535
Bad     : 0
Missed  : 0
Locked  : 0
Unknown : 0
Deleted : 0
